[features]
seeds = false
skip-lint = false
[programs.localnet]
sf2 = "6py5B26QgfhBzRhPtUd8kwB8jrwmGa9vfnNxtjHjpzLP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/goksen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
